import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "@/app/components/navigationBar";
import Wrapper from "./wrapper";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="min-h-[100vh] w-full   flex pt-2 px-2  flex-col">
          <ThemeProvider
              attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Wrapper>

        {children}
        </Wrapper>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
